/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use reqwest;

use super::{configuration, Error};
use crate::http::apis::ResponseContent;

/// struct for passing parameters to the method [`create_employees_resource`]
#[derive(Clone, Debug, Default)]
pub struct CreateEmployeesResourceParams {
    /// employee to create
    pub employee: Option<crate::http::models::EmployeeWrap>,
}

/// struct for passing parameters to the method [`get_employees_resource`]
#[derive(Clone, Debug, Default)]
pub struct GetEmployeesResourceParams {
    /// identifies the employee
    pub employee_id: String,
}

/// struct for passing parameters to the method [`update_employees_resource`]
#[derive(Clone, Debug, Default)]
pub struct UpdateEmployeesResourceParams {
    /// identifies the employee
    pub employee_id: String,
    /// employee to update
    pub employee: Option<crate::http::models::EmployeeWrap>,
}

/// struct for typed errors of method [`create_employees_resource`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateEmployeesResourceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_employees_resource`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEmployeesResourceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_employees_resource`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEmployeesResourceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_employees_resource`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateEmployeesResourceError {
    UnknownValue(serde_json::Value),
}

/// EmployeeId is optional. If not supplied the program will generate a unique id.   Only one of DatedSchedules and ScheduleId may be supplied. If DatedSchedules are supplied  it must have one and only one record where FirstDay = '1970-01-01'.  All FirstDay values must greater or equal to '1970-01-01' and unique.   If DatedWages is supplied neither MonthlySalary nor HourlyPay may be supplied. If  MonthlySalary or HourlyPay are supplied, DatedWages may not be supplied.  If DatedWages are supplied it must have one and only one record where FirstDay = '1970-01-01'.  All FirstDay values must greater or equal to '1970-01-01' and unique.
pub async fn create_employees_resource(
    configuration: &configuration::Configuration,
    params: CreateEmployeesResourceParams,
) -> Result<crate::http::models::EmployeeWrap, Error<CreateEmployeesResourceError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let employee = params.employee;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/3/employees/", local_var_configuration.base_path);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    local_var_req_builder = local_var_req_builder.json(&employee);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<CreateEmployeesResourceError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// ScheduleId, MonthlySalary and HourlyPay reflect current values, all  ScheduleIds are returned in DatedSchedules and all MonthlySalary and  HourlyPay pairs are returned in DatedWages.
pub async fn get_employees_resource(
    configuration: &configuration::Configuration,
    params: GetEmployeesResourceParams,
) -> Result<crate::http::models::EmployeeWrap, Error<GetEmployeesResourceError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let employee_id = params.employee_id;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/3/employees/{EmployeeId}",
        local_var_configuration.base_path,
        EmployeeId = crate::http::apis::urlencode(employee_id)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetEmployeesResourceError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// ScheduleId, MonthlySalary and HourlyPay reflect current values, all  ScheduleIds are returned in DatedSchedules and all MonthlySalary and  HourlyPay pairs are returned in DatedWages.
pub async fn list_employees_resource(
    configuration: &configuration::Configuration,
) -> Result<crate::http::models::EmployeeListItemWrap, Error<ListEmployeesResourceError>> {
    let local_var_configuration = configuration;

    // unbox the parameters

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/3/employees/", local_var_configuration.base_path);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<ListEmployeesResourceError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Only one of DatedSchedules and ScheduleId may be supplied. If DatedSchedules are supplied  it must have one and only one record where FirstDay = '1970-01-01'.  All FirstDay values must greater or equal to '1970-01-01' and unique.   If DatedWages is supplied neither MonthlySalary nor HourlyPay may be supplied. If  MonthlySalary or HourlyPay are supplied, DatedWages may not be supplied.  If DatedWages are supplied it must have one and only one record where FirstDay = '1970-01-01'.  All FirstDay values must greater or equal to '1970-01-01' and unique.
pub async fn update_employees_resource(
    configuration: &configuration::Configuration,
    params: UpdateEmployeesResourceParams,
) -> Result<crate::http::models::EmployeeWrap, Error<UpdateEmployeesResourceError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let employee_id = params.employee_id;
    let employee = params.employee;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/3/employees/{EmployeeId}",
        local_var_configuration.base_path,
        EmployeeId = crate::http::apis::urlencode(employee_id)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    local_var_req_builder = local_var_req_builder.json(&employee);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<UpdateEmployeesResourceError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}
