/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ArticleListItem {
    #[serde(rename = "@url", skip_serializing_if = "Option::is_none")]
    pub at_url: Option<String>,
    #[serde(rename = "ArticleNumber", skip_serializing_if = "Option::is_none")]
    pub article_number: Option<String>,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "DisposableQuantity", skip_serializing_if = "Option::is_none")]
    pub disposable_quantity: Option<String>,
    #[serde(rename = "EAN", skip_serializing_if = "Option::is_none")]
    pub ean: Option<String>,
    #[serde(rename = "Housework", skip_serializing_if = "Option::is_none")]
    pub housework: Option<bool>,
    #[serde(rename = "PurchasePrice", skip_serializing_if = "Option::is_none")]
    pub purchase_price: Option<String>,
    #[serde(rename = "SalesPrice", skip_serializing_if = "Option::is_none")]
    pub sales_price: Option<String>,
    #[serde(rename = "QuantityInStock", skip_serializing_if = "Option::is_none")]
    pub quantity_in_stock: Option<f64>,
    #[serde(rename = "ReservedQuantity", skip_serializing_if = "Option::is_none")]
    pub reserved_quantity: Option<String>,
    #[serde(rename = "StockPlace", skip_serializing_if = "Option::is_none")]
    pub stock_place: Option<String>,
    #[serde(rename = "StockValue", skip_serializing_if = "Option::is_none")]
    pub stock_value: Option<String>,
    #[serde(rename = "Unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(rename = "VAT", skip_serializing_if = "Option::is_none")]
    pub vat: Option<String>,
    #[serde(rename = "WebshopArticle", skip_serializing_if = "Option::is_none")]
    pub webshop_article: Option<bool>,
}

impl ArticleListItem {
    pub fn new(description: String) -> ArticleListItem {
        ArticleListItem {
            at_url: None,
            article_number: None,
            description,
            disposable_quantity: None,
            ean: None,
            housework: None,
            purchase_price: None,
            sales_price: None,
            quantity_in_stock: None,
            reserved_quantity: None,
            stock_place: None,
            stock_value: None,
            unit: None,
            vat: None,
            webshop_article: None,
        }
    }
}
