/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceInvoiceRow {
    #[serde(rename = "AccountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<i32>,
    #[serde(rename = "ArticleNumber", skip_serializing_if = "Option::is_none")]
    pub article_number: Option<String>,
    #[serde(
        rename = "ContributionPercent",
        skip_serializing_if = "Option::is_none"
    )]
    pub contribution_percent: Option<String>,
    #[serde(rename = "ContributionValue", skip_serializing_if = "Option::is_none")]
    pub contribution_value: Option<String>,
    #[serde(rename = "CostCenter", skip_serializing_if = "Option::is_none")]
    pub cost_center: Option<String>,
    #[serde(rename = "DeliveredQuantity", skip_serializing_if = "Option::is_none")]
    pub delivered_quantity: Option<String>,
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "Discount", skip_serializing_if = "Option::is_none")]
    pub discount: Option<f64>,
    #[serde(rename = "DiscountType", skip_serializing_if = "Option::is_none")]
    pub discount_type: Option<DiscountType>,
    #[serde(rename = "HouseWork", skip_serializing_if = "Option::is_none")]
    pub house_work: Option<bool>,
    #[serde(
        rename = "HouseWorkHoursToReport",
        skip_serializing_if = "Option::is_none"
    )]
    pub house_work_hours_to_report: Option<i32>,
    #[serde(rename = "HouseWorkType", skip_serializing_if = "Option::is_none")]
    pub house_work_type: Option<HouseWorkType>,
    #[serde(rename = "Price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(rename = "PriceExcludingVAT", skip_serializing_if = "Option::is_none")]
    pub price_excluding_vat: Option<f64>,
    #[serde(rename = "Project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "RowId", skip_serializing_if = "Option::is_none")]
    pub row_id: Option<i32>,
    #[serde(rename = "StockPointCode", skip_serializing_if = "Option::is_none")]
    pub stock_point_code: Option<String>,
    #[serde(rename = "Total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    #[serde(rename = "TotalExcludingVAT", skip_serializing_if = "Option::is_none")]
    pub total_excluding_vat: Option<f64>,
    #[serde(rename = "Unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(rename = "VAT", skip_serializing_if = "Option::is_none")]
    pub vat: Option<i32>,
}

impl InvoiceInvoiceRow {
    pub fn new() -> InvoiceInvoiceRow {
        InvoiceInvoiceRow {
            account_number: None,
            article_number: None,
            contribution_percent: None,
            contribution_value: None,
            cost_center: None,
            delivered_quantity: None,
            description: None,
            discount: None,
            discount_type: None,
            house_work: None,
            house_work_hours_to_report: None,
            house_work_type: None,
            price: None,
            price_excluding_vat: None,
            project: None,
            row_id: None,
            stock_point_code: None,
            total: None,
            total_excluding_vat: None,
            unit: None,
            vat: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DiscountType {
    #[serde(rename = "AMOUNT")]
    Amount,
    #[serde(rename = "PERCENT")]
    Percent,
}

impl Default for DiscountType {
    fn default() -> DiscountType {
        Self::Amount
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HouseWorkType {
    #[serde(rename = "CONSTRUCTION")]
    Construction,
    #[serde(rename = "ELECTRICITY")]
    Electricity,
    #[serde(rename = "GLASSMETALWORK")]
    Glassmetalwork,
    #[serde(rename = "GROUNDDRAINAGEWORK")]
    Grounddrainagework,
    #[serde(rename = "MASONRY")]
    Masonry,
    #[serde(rename = "PAINTINGWALLPAPERING")]
    Paintingwallpapering,
    #[serde(rename = "HVAC")]
    Hvac,
    #[serde(rename = "MAJORAPPLIANCEREPAIR")]
    Majorappliancerepair,
    #[serde(rename = "MOVINGSERVICES")]
    Movingservices,
    #[serde(rename = "ITSERVICES")]
    Itservices,
    #[serde(rename = "CLEANING")]
    Cleaning,
    #[serde(rename = "TEXTILECLOTHING")]
    Textileclothing,
    #[serde(rename = "SNOWPLOWING")]
    Snowplowing,
    #[serde(rename = "GARDENING")]
    Gardening,
    #[serde(rename = "BABYSITTING")]
    Babysitting,
    #[serde(rename = "OTHERCARE")]
    Othercare,
    #[serde(rename = "OTHERCOSTS")]
    Othercosts,
    #[serde(rename = "SOLARCELLS")]
    Solarcells,
    #[serde(rename = "STORAGESELFPRODUCEDELECTRICITY")]
    Storageselfproducedelectricity,
    #[serde(rename = "CHARGINGSTATIONELECTRICVEHICLE")]
    Chargingstationelectricvehicle,
    #[serde(rename = "HOMEMAINTENANCE")]
    Homemaintenance,
    #[serde(rename = "FURNISHING")]
    Furnishing,
    #[serde(rename = "TRANSPORTATIONSERVICES")]
    Transportationservices,
    #[serde(rename = "WASHINGANDCAREOFCLOTHING")]
    Washingandcareofclothing,
}

impl Default for HouseWorkType {
    fn default() -> HouseWorkType {
        Self::Construction
    }
}
