/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */
use crate::http::deserialize_bool_from_string;
use crate::http::deserialize_number_from_string;
use crate::http::deserialize_string_from_number;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SupplierInvoiceListItem {
    #[serde(rename = "@url", skip_serializing_if = "Option::is_none")]
    pub at_url: Option<String>,
    #[serde(
        rename = "Balance",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_number_from_string"
    )]
    pub balance: Option<f64>,
    #[serde(rename = "Booked", skip_serializing_if = "Option::is_none")]
    pub booked: Option<bool>,
    #[serde(rename = "Cancel", skip_serializing_if = "Option::is_none")]
    pub cancel: Option<bool>,
    #[serde(
        rename = "Cancelled",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_bool_from_string",
        default
    )]
    pub cancelled: Option<bool>,
    #[serde(rename = "CostCenter", skip_serializing_if = "Option::is_none")]
    pub cost_center: Option<String>,
    #[serde(
        rename = "Credit",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_bool_from_string"
    )]
    pub credit: Option<bool>,
    #[serde(
        rename = "CreditReference",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_string_from_number",
        default
    )]
    pub credit_reference: Option<String>,
    #[serde(rename = "Currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(rename = "CurrencyRate", skip_serializing_if = "Option::is_none")]
    pub currency_rate: Option<String>,
    #[serde(rename = "CurrencyUnit", skip_serializing_if = "Option::is_none")]
    pub currency_unit: Option<f64>,
    #[serde(rename = "DueDate", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    #[serde(
        rename = "ExternalInvoiceNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_invoice_number: Option<String>,
    #[serde(
        rename = "ExternalInvoiceSeries",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_invoice_series: Option<String>,
    #[serde(rename = "GivenNumber", skip_serializing_if = "Option::is_none")]
    pub given_number: Option<String>,
    #[serde(rename = "InvoiceDate", skip_serializing_if = "Option::is_none")]
    pub invoice_date: Option<String>,
    #[serde(rename = "InvoiceNumber", skip_serializing_if = "Option::is_none")]
    pub invoice_number: Option<String>,
    #[serde(rename = "Project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "SupplierNumber")]
    pub supplier_number: String,
    #[serde(rename = "SupplierName", skip_serializing_if = "Option::is_none")]
    pub supplier_name: Option<String>,
    #[serde(rename = "Total", skip_serializing_if = "Option::is_none")]
    pub total: Option<String>,
    #[serde(rename = "AuthorizerName", skip_serializing_if = "Option::is_none")]
    pub authorizer_name: Option<String>,
    #[serde(rename = "Vouchers", skip_serializing_if = "Option::is_none")]
    pub vouchers: Option<Vec<crate::http::models::SupplierInvoiceListItemVoucher>>,
    #[serde(rename = "FinalPayDate", skip_serializing_if = "Option::is_none")]
    pub final_pay_date: Option<String>,
    #[serde(rename = "OCR", skip_serializing_if = "Option::is_none")]
    pub ocr: Option<String>,
}
