/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TaxReduction {
    #[serde(rename = "@url", skip_serializing_if = "Option::is_none")]
    pub at_url: Option<String>,
    #[serde(rename = "ApprovedAmount", skip_serializing_if = "Option::is_none")]
    pub approved_amount: Option<f64>,
    #[serde(rename = "AskedAmount")]
    pub asked_amount: f64,
    #[serde(rename = "BilledAmount", skip_serializing_if = "Option::is_none")]
    pub billed_amount: Option<f64>,
    #[serde(rename = "CustomerName")]
    pub customer_name: String,
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(
        rename = "PropertyDesignation",
        skip_serializing_if = "Option::is_none"
    )]
    pub property_designation: Option<String>,
    #[serde(rename = "ReferenceDocumentType")]
    pub reference_document_type: ReferenceDocumentType,
    #[serde(rename = "ReferenceNumber")]
    pub reference_number: String,
    #[serde(rename = "RequestSent", skip_serializing_if = "Option::is_none")]
    pub request_sent: Option<bool>,
    #[serde(
        rename = "ResidenceAssociationOrganisationNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub residence_association_organisation_number: Option<String>,
    #[serde(rename = "SocialSecurityNumber")]
    pub social_security_number: String,
    #[serde(rename = "VoucherNumber", skip_serializing_if = "Option::is_none")]
    pub voucher_number: Option<i32>,
    #[serde(rename = "VoucherSeries", skip_serializing_if = "Option::is_none")]
    pub voucher_series: Option<String>,
    #[serde(rename = "VoucherYear", skip_serializing_if = "Option::is_none")]
    pub voucher_year: Option<i32>,
    #[serde(
        rename = "TaxReductionAmounts",
        skip_serializing_if = "Option::is_none"
    )]
    pub tax_reduction_amounts: Option<Vec<crate::http::models::TaxReductionTaxReductionAmount>>,
}

impl TaxReduction {
    pub fn new(
        asked_amount: f64,
        customer_name: String,
        reference_document_type: ReferenceDocumentType,
        reference_number: String,
        social_security_number: String,
    ) -> TaxReduction {
        TaxReduction {
            at_url: None,
            approved_amount: None,
            asked_amount,
            billed_amount: None,
            customer_name,
            id: None,
            property_designation: None,
            reference_document_type,
            reference_number,
            request_sent: None,
            residence_association_organisation_number: None,
            social_security_number,
            voucher_number: None,
            voucher_series: None,
            voucher_year: None,
            tax_reduction_amounts: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReferenceDocumentType {
    #[serde(rename = "OFFER")]
    Offer,
    #[serde(rename = "ORDER")]
    Order,
    #[serde(rename = "INVOICE")]
    Invoice,
}

impl Default for ReferenceDocumentType {
    fn default() -> ReferenceDocumentType {
        Self::Offer
    }
}
