/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Voucher {
    #[serde(rename = "@url", skip_serializing_if = "Option::is_none")]
    pub at_url: Option<String>,
    #[serde(rename = "Comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "CostCenter", skip_serializing_if = "Option::is_none")]
    pub cost_center: Option<String>,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "Project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "ReferenceNumber", skip_serializing_if = "Option::is_none")]
    pub reference_number: Option<String>,
    #[serde(rename = "ReferenceType", skip_serializing_if = "Option::is_none")]
    pub reference_type: Option<ReferenceType>,
    #[serde(rename = "TransactionDate")]
    pub transaction_date: String,
    #[serde(rename = "VoucherNumber", skip_serializing_if = "Option::is_none")]
    pub voucher_number: Option<i32>,
    #[serde(rename = "VoucherRows", skip_serializing_if = "Option::is_none")]
    pub voucher_rows: Option<Vec<crate::http::models::VoucherVoucherRow>>,
    #[serde(rename = "VoucherSeries")]
    pub voucher_series: String,
    #[serde(rename = "Year")]
    pub year: i32,
    #[serde(rename = "ApprovalState", skip_serializing_if = "Option::is_none")]
    pub approval_state: Option<i32>,
}

impl Voucher {
    pub fn new(
        description: String,
        transaction_date: String,
        voucher_series: String,
        year: i32,
    ) -> Voucher {
        Voucher {
            at_url: None,
            comments: None,
            cost_center: None,
            description,
            project: None,
            reference_number: None,
            reference_type: None,
            transaction_date,
            voucher_number: None,
            voucher_rows: None,
            voucher_series,
            year,
            approval_state: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReferenceType {
    #[serde(rename = "INVOICE")]
    Invoice,
    #[serde(rename = "SUPPLIERINVOICE")]
    Supplierinvoice,
    #[serde(rename = "INVOICEPAYMENT")]
    Invoicepayment,
    #[serde(rename = "SUPPLIERPAYMENT")]
    Supplierpayment,
    #[serde(rename = "MANUAL")]
    Manual,
    #[serde(rename = "CASHINVOICE")]
    Cashinvoice,
    #[serde(rename = "ACCRUAL")]
    Accrual,
}

impl Default for ReferenceType {
    fn default() -> ReferenceType {
        Self::Invoice
    }
}
