/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetType {
    #[serde(rename = "@url", skip_serializing_if = "Option::is_none")]
    pub at_url: Option<String>,
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "Number", skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "Notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    #[serde(rename = "InUse", skip_serializing_if = "Option::is_none")]
    pub in_use: Option<bool>,
    #[serde(rename = "AccountAssetId", skip_serializing_if = "Option::is_none")]
    pub account_asset_id: Option<i32>,
    #[serde(rename = "AccountValueLossId", skip_serializing_if = "Option::is_none")]
    pub account_value_loss_id: Option<i32>,
    #[serde(rename = "AccountSaleLossId", skip_serializing_if = "Option::is_none")]
    pub account_sale_loss_id: Option<i32>,
    #[serde(rename = "AccountSaleWinId", skip_serializing_if = "Option::is_none")]
    pub account_sale_win_id: Option<i32>,
    #[serde(
        rename = "AccountRevaluationId",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_revaluation_id: Option<i32>,
    #[serde(
        rename = "AccountWriteDownAckId",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_write_down_ack_id: Option<i32>,
    #[serde(rename = "AccountWriteDownId", skip_serializing_if = "Option::is_none")]
    pub account_write_down_id: Option<i32>,
    #[serde(
        rename = "AccountDepreciationId",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_depreciation_id: Option<i32>,
    #[serde(rename = "AccountAsset", skip_serializing_if = "Option::is_none")]
    pub account_asset: Option<i32>,
    #[serde(rename = "AccountValueLoss", skip_serializing_if = "Option::is_none")]
    pub account_value_loss: Option<i32>,
    #[serde(rename = "AccountSaleLoss", skip_serializing_if = "Option::is_none")]
    pub account_sale_loss: Option<i32>,
    #[serde(rename = "AccountSaleWin", skip_serializing_if = "Option::is_none")]
    pub account_sale_win: Option<i32>,
    #[serde(rename = "AccountRevaluation", skip_serializing_if = "Option::is_none")]
    pub account_revaluation: Option<i32>,
    #[serde(
        rename = "AccountWriteDownAck",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_write_down_ack: Option<i32>,
    #[serde(rename = "AccountWriteDown", skip_serializing_if = "Option::is_none")]
    pub account_write_down: Option<i32>,
    #[serde(
        rename = "AccountDepreciation",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_depreciation: Option<i32>,
}

impl AssetType {
    pub fn new() -> AssetType {
        AssetType {
            at_url: None,
            id: None,
            number: None,
            description: None,
            notes: None,
            r#type: None,
            in_use: None,
            account_asset_id: None,
            account_value_loss_id: None,
            account_sale_loss_id: None,
            account_sale_win_id: None,
            account_revaluation_id: None,
            account_write_down_ack_id: None,
            account_write_down_id: None,
            account_depreciation_id: None,
            account_asset: None,
            account_value_loss: None,
            account_sale_loss: None,
            account_sale_win: None,
            account_revaluation: None,
            account_write_down_ack: None,
            account_write_down: None,
            account_depreciation: None,
        }
    }
}
