/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomingGoodsRow {
    #[serde(rename = "itemId")]
    pub item_id: String,
    #[serde(rename = "receivedQuantity")]
    pub received_quantity: f32,
    #[serde(rename = "backOrderQuantity")]
    pub back_order_quantity: f32,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "itemDescription", skip_serializing_if = "Option::is_none")]
    pub item_description: Option<String>,
    #[serde(rename = "stockPointId", skip_serializing_if = "Option::is_none")]
    pub stock_point_id: Option<uuid::Uuid>,
    #[serde(rename = "stockPointCode", skip_serializing_if = "Option::is_none")]
    pub stock_point_code: Option<String>,
    #[serde(rename = "stockPointName", skip_serializing_if = "Option::is_none")]
    pub stock_point_name: Option<String>,
    #[serde(rename = "stockLocationId", skip_serializing_if = "Option::is_none")]
    pub stock_location_id: Option<uuid::Uuid>,
    #[serde(rename = "stockLocationCode", skip_serializing_if = "Option::is_none")]
    pub stock_location_code: Option<String>,
    #[serde(rename = "stockLocationName", skip_serializing_if = "Option::is_none")]
    pub stock_location_name: Option<String>,
    #[serde(rename = "takenQuantity")]
    pub taken_quantity: f32,
    #[serde(rename = "costCenterCode", skip_serializing_if = "Option::is_none")]
    pub cost_center_code: Option<String>,
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(rename = "invoicedQuantity")]
    pub invoiced_quantity: f32,
    #[serde(rename = "itemUnit", skip_serializing_if = "Option::is_none")]
    pub item_unit: Option<String>,
    #[serde(rename = "purchaseOrderId", skip_serializing_if = "Option::is_none")]
    pub purchase_order_id: Option<i64>,
    #[serde(rename = "orderedQuantity")]
    pub ordered_quantity: f32,
    #[serde(rename = "purchaseOrderRowId", skip_serializing_if = "Option::is_none")]
    pub purchase_order_row_id: Option<uuid::Uuid>,
    #[serde(rename = "rowOrder", skip_serializing_if = "Option::is_none")]
    pub row_order: Option<i32>,
    #[serde(rename = "batch", skip_serializing_if = "Option::is_none")]
    pub batch: Option<String>,
    #[serde(rename = "isStockItem", skip_serializing_if = "Option::is_none")]
    pub is_stock_item: Option<bool>,
    #[serde(
        rename = "remainingOrderedQuantity",
        skip_serializing_if = "Option::is_none"
    )]
    pub remaining_ordered_quantity: Option<f32>,
    #[serde(rename = "directCost", skip_serializing_if = "Option::is_none")]
    pub direct_cost: Option<f32>,
}

impl IncomingGoodsRow {
    pub fn new(
        item_id: String,
        received_quantity: f32,
        back_order_quantity: f32,
        taken_quantity: f32,
        invoiced_quantity: f32,
        ordered_quantity: f32,
    ) -> IncomingGoodsRow {
        IncomingGoodsRow {
            item_id,
            received_quantity,
            back_order_quantity,
            id: None,
            item_description: None,
            stock_point_id: None,
            stock_point_code: None,
            stock_point_name: None,
            stock_location_id: None,
            stock_location_code: None,
            stock_location_name: None,
            taken_quantity,
            cost_center_code: None,
            project_id: None,
            invoiced_quantity,
            item_unit: None,
            purchase_order_id: None,
            ordered_quantity,
            purchase_order_row_id: None,
            row_order: None,
            batch: None,
            is_stock_item: None,
            remaining_ordered_quantity: None,
            direct_cost: None,
        }
    }
}
