/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PurchaseOrderRow {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "purchaseOrderId", skip_serializing_if = "Option::is_none")]
    pub purchase_order_id: Option<i64>,
    #[serde(rename = "itemId")]
    pub item_id: String,
    #[serde(rename = "orderedQuantity")]
    pub ordered_quantity: f32,
    #[serde(rename = "itemDescription", skip_serializing_if = "Option::is_none")]
    pub item_description: Option<String>,
    #[serde(rename = "itemUnit", skip_serializing_if = "Option::is_none")]
    pub item_unit: Option<String>,
    #[serde(rename = "rowNum", skip_serializing_if = "Option::is_none")]
    pub row_num: Option<i64>,
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(rename = "costCenterCode", skip_serializing_if = "Option::is_none")]
    pub cost_center_code: Option<String>,
    #[serde(rename = "remainingOrderedQuantity")]
    pub remaining_ordered_quantity: f32,
    #[serde(rename = "currencyCode")]
    pub currency_code: String,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f32>,
    #[serde(rename = "receivedQuantity", skip_serializing_if = "Option::is_none")]
    pub received_quantity: Option<f32>,
    #[serde(rename = "backOrderQuantity", skip_serializing_if = "Option::is_none")]
    pub back_order_quantity: Option<f32>,
    #[serde(rename = "stockPointId", skip_serializing_if = "Option::is_none")]
    pub stock_point_id: Option<uuid::Uuid>,
    #[serde(rename = "stockLocationId", skip_serializing_if = "Option::is_none")]
    pub stock_location_id: Option<uuid::Uuid>,
    #[serde(rename = "stockPointCode", skip_serializing_if = "Option::is_none")]
    pub stock_point_code: Option<String>,
    #[serde(rename = "stockPointName", skip_serializing_if = "Option::is_none")]
    pub stock_point_name: Option<String>,
    #[serde(rename = "stockLocationCode", skip_serializing_if = "Option::is_none")]
    pub stock_location_code: Option<String>,
    #[serde(rename = "stockLocationName", skip_serializing_if = "Option::is_none")]
    pub stock_location_name: Option<String>,
    #[serde(rename = "isStockItem", skip_serializing_if = "Option::is_none")]
    pub is_stock_item: Option<bool>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Vec<crate::models::PurchaseOrderRowNote>>,
}

impl PurchaseOrderRow {
    pub fn new(
        item_id: String,
        ordered_quantity: f32,
        remaining_ordered_quantity: f32,
        currency_code: String,
    ) -> PurchaseOrderRow {
        PurchaseOrderRow {
            id: None,
            purchase_order_id: None,
            item_id,
            ordered_quantity,
            item_description: None,
            item_unit: None,
            row_num: None,
            project_id: None,
            cost_center_code: None,
            remaining_ordered_quantity,
            currency_code,
            price: None,
            received_quantity: None,
            back_order_quantity: None,
            stock_point_id: None,
            stock_location_id: None,
            stock_point_code: None,
            stock_point_name: None,
            stock_location_code: None,
            stock_location_name: None,
            is_stock_item: None,
            notes: None,
        }
    }
}
