/*
 * # Documentation   The Fortnox API is organized around REST. This means that we’ve designed it to have resource-oriented URLs and be as predictable as possible for you as developer.  It also means that we use HTTP status codes when something goes wrong and HTTP verbs understod by many API clients around the web.  We use a modified version of OAuth2 for authentication to offer a secure way for both you and our users to interact.  The API is generally built to support both XML and JSON but in this documentation all the examples will be in JSON.  We encourage you to read all the articles in the [general information section](https://developer.fortnox.se/general/)</a> first, before going forward and learning about the different resources.  This to ensure you get an understanding of some of the shared components of the API such as parameters and error handling.  ## Rate limits  The limit is 4 requests per second per access-token. This equals to a bit more than 200 requests per minute.  [Read more about this here.](https://developer.fortnox.se/general/regarding-fortnox-api-rate-limits/)  ## Query parameters  Use query parameters with the ?-character and separate parameters with the &-character.   **Example:**  GET - https://api.fortnox.se/3/invoices?accountnumberfrom=3000&accountnumberto=4000 Read more about our parameters [here](https://developer.fortnox.se/general/parameters/)   Search the documentation using the search field in the top left corner.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StockPoint {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "stockLocations", skip_serializing_if = "Option::is_none")]
    pub stock_locations: Option<Vec<crate::models::StockLocation>>,
    #[serde(
        rename = "usingCompanyAddress",
        skip_serializing_if = "Option::is_none"
    )]
    pub using_company_address: Option<bool>,
    #[serde(rename = "deliveryName", skip_serializing_if = "Option::is_none")]
    pub delivery_name: Option<String>,
    #[serde(rename = "deliveryAddress", skip_serializing_if = "Option::is_none")]
    pub delivery_address: Option<String>,
    #[serde(rename = "deliveryAddress2", skip_serializing_if = "Option::is_none")]
    pub delivery_address2: Option<String>,
    #[serde(rename = "deliveryZipCode", skip_serializing_if = "Option::is_none")]
    pub delivery_zip_code: Option<String>,
    #[serde(rename = "deliveryCity", skip_serializing_if = "Option::is_none")]
    pub delivery_city: Option<String>,
    #[serde(rename = "deliveryPhone", skip_serializing_if = "Option::is_none")]
    pub delivery_phone: Option<String>,
    #[serde(
        rename = "deliveryCountryCode",
        skip_serializing_if = "Option::is_none"
    )]
    pub delivery_country_code: Option<String>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl StockPoint {
    pub fn new(code: String, name: String) -> StockPoint {
        StockPoint {
            id: None,
            code,
            name,
            stock_locations: None,
            using_company_address: None,
            delivery_name: None,
            delivery_address: None,
            delivery_address2: None,
            delivery_zip_code: None,
            delivery_city: None,
            delivery_phone: None,
            delivery_country_code: None,
            active: None,
        }
    }
}
